spring.application.name=Re-Stream

spring.eureka.service-url.defaultZone= http://43.204.150.3:8761/eureka/
eureka.instance.prefer-ip-address=true
fail-fast= true

spring.datasource.url=jdbc:postgresql://35.154.6.99:5432/videostream
spring.datasource.username=maisarali
spring.datasource.password=Khaali.dabba123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.mongodb.uri=mongodb://43.204.150.3:27017/stream-video

# JPA (Hibernate) Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.stream.base-directory=/home/ubuntu/Videostream/video
app.stream.hls-url-prefix= http://43.204.150.3:8082/stream/
