spring.application.name=Re-Stream
server.port=8071
eureka.instance.prefer-ip-address=true
spring.cloud.client.ip-address=127.0.0.1

spring.eureka.service-url.defaultZone= http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
fail-fast= true

# Datasource Configuration for local
spring.datasource.url=jdbc:postgresql://localhost:5432/Videostream
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.mongodb.primary.uri=mongodb://localhost:27017/vidpress
spring.data.mongodb.secondary.uri=mongodb://localhost:27017/recordings
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis



# Email Config (Use SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahsharali786@gmail.com
spring.mail.password=dijb sznv zrdo axeu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA (Hibernate) Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.stream.base-directory=D:/Videostream/video
app.stream.recording-directory=D:/Recording/
app.stream.hls-url-prefix= http://localhost:8082/stream/

#minIO configuration
amazon.aws.accessKey=FNyqsd5pmbPpPXYbC0jj
amazon.aws.secretKey=jobN5Df2SwcMpG4ZC4GHsnYTvNYod4QqnbD7npct
amazon.aws.bucket=video-recording





# Remote server settings
remote.server.enabled=true
remote.server.host=35.223.127.154
remote.server.port=22
remote.server.username=maisar
remote.server.private.key.path=C:/Users/Maisar/.ssh/id_rsa
remote.server.private.key.passphrase=
remote.server.base.directory=/var/www/recordings

# Set to true if you want to delete local recordings after successful transfer
recording.delete.after.transfer=false
