spring.application.name=Re-Stream

spring.eureka.service-url.defaultZone= http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.profiles.active= local
spring.config.uri= http://localhost:8888
fail-fast= true
