spring.application.name=Re-Stream

// spring.eureka.service-url.defaultZone= http://localhost:8761/eureka/
// eureka.instance.prefer-ip-address=true
// fail-fast= true

# Datasource Configuration for local
spring.datasource.url=jdbc:postgresql://localhost:5432/Videostream
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.mongodb.primary.uri=mongodb://localhost:27017/vidpress
spring.data.mongodb.secondary.uri=mongodb://localhost:27017/recordings

# JPA (Hibernate) Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.stream.base-directory=D:/Videostream/video
app.stream.recording-directory=D:/Recording/video
app.stream.hls-url-prefix= http://localhost:8082/stream/
